export const ADD_SERVICE = "ADD_SERVICE";
export const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_FAILED = "ADD_SERVICE_FAILED";
export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICES_FAILED = "GET_SERVICES_FAILED";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";